language: generic

matrix:
  include:
    - os: osx
      language: swift
      osx_image: xcode10.2
      script:
        - brew install libressl
        - swift build
        - swift test --parallel -Xswiftc -DDEBUG
